# Generated by Django 5.0.2 on 2024-03-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
