# Generated by Django 5.0.2 on 2024-03-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0002_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
