# Generated by Django 5.0.2 on 2024-03-28 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0004_remove_user_is_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('permission', models.FileField(null=True, upload_to='documents/')),
                ('social_media', models.TextField(max_length=200, null=True)),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_page.user')),
            ],
        ),
    ]
