# Generated by Django 5.0.2 on 2024-03-29 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityPage', '0004_alter_communities_sellers'),
        ('register_page', '0005_alter_user_email_alter_user_password_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communityPage.communities'),
        ),
    ]
