# Generated by Django 5.0.2 on 2024-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0006_seller_seller_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
