# Generated by Django 5.2.6 on 2025-10-04 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityPage', '0005_community_communityseller'),
        ('register_page', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communityPage.community'),
        ),
    ]
