# Generated by Django 5.0.3 on 2024-03-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sellers', models.IntegerField()),
                ('products', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='Images')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
