# Generated by Django 5.0.2 on 2024-03-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityPage', '0003_alter_communities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='sellers',
            field=models.IntegerField(null=True),
        ),
    ]
