# Generated by Django 5.2.6 on 2025-10-04 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0009_seller_active_seller'),
        ('communityPage', '0005_community_communityseller'),
        ('register_page', '0009_alter_seller_seller_community'),
    ]

    operations = [
        migrations.DeleteModel(
            name='communities',
        ),
        migrations.AddField(
            model_name='communityseller',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communityPage.community'),
        ),
        migrations.AddField(
            model_name='communityseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerprofile.seller'),
        ),
        migrations.AlterUniqueTogether(
            name='communityseller',
            unique_together={('community', 'seller')},
        ),
    ]
