# Generated by Django 5.0.3 on 2024-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
