# Generated by Django 5.0.2 on 2024-04-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0005_seller_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='photo',
            field=models.ImageField(null=True, upload_to='seller_photos/'),
        ),
    ]
