# Generated by Django 5.0.2 on 2024-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0008_alter_seller_age_alter_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='active_seller',
            field=models.BooleanField(default=False),
        ),
    ]
