# Generated by Django 5.0.2 on 2024-04-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0002_seller_age_seller_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photos/'),
        ),
    ]
