# Generated by Django 5.0.2 on 2024-03-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='Images')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
