# Generated by Django 5.0.2 on 2024-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='products_images'),
        ),
    ]
