# Generated by Django 5.0.2 on 2024-03-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_main_page', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
