# Generated by Django 4.2.7 on 2024-05-02 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0009_seller_active_seller'),
        ('community_main_page', '0003_rename_productseller_productuser'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='productuser',
            name='product_info',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community_main_page.products'),
        ),
    ]
