# Generated by Django 5.0.2 on 2024-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_main_page', '0008_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
