# Generated by Django 5.0.2 on 2024-04-13 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_main_page', '0012_images_generated_products_image_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image_generated',
        ),
        migrations.DeleteModel(
            name='images_generated',
        ),
    ]
