# Generated by Django 5.0.2 on 2024-04-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_main_page', '0013_remove_products_image_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
