# Generated by Django 5.0.2 on 2024-04-14 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_main_page', '0002_productseller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSeller',
            new_name='ProductUser',
        ),
    ]
