# Generated by Django 5.0.2 on 2024-05-08 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerprofile', '0009_seller_active_seller'),
        ('community_main_page', '0005_products_seller_info_alter_productuser_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sellerprofile.seller'),
        ),
    ]
