# Generated by Django 5.2.6 on 2025-10-04 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityPage', '0006_delete_communities_communityseller_community_and_more'),
        ('community_main_page', '0007_product_alter_productuser_product_info_productrating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communityPage.community'),
        ),
    ]
