# Generated by Django 5.0.3 on 2024-03-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='communities',
        ),
    ]
