# Generated by Django 4.2.7 on 2024-03-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityPage', '0002_rename_products_communities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
