# Generated by Django 5.0.2 on 2024-03-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_page', '0003_user_is_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_seller',
        ),
    ]
